spring:
  application:
    name: auth-session
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/auth_session?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: psw_auth
    password: auth1234!

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true