spring:
  application:
    name: auth-session
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true